openapi: 0.0.1
info:
  title: legacy-identity-password-validation-api-v1
  description: >-
    The functionality is to facilitate Advisor Hub with validation of password characters based on its positions.
  version: '0.1'

servers: 
  - url: 'https://apip.intra-robt.bt.com:53080/legacy/v1/identity-password-validation'
    description: Production
paths:
  '/password':
    $ref:  './paths/putPassword.yaml'
components:
  securitySchemes:
    <p>This API supports TLS mutual authentication.</p>
